version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint-test-scan:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn ci:lint
            - run: yarn ci:test
            - run: yarn ci:scan
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
workflows:
    lint-test-scan:
      jobs:
        - lint-test-scan